name: Cleanup Old Images
on:
  schedule:
    - cron: "15 0 * * 0" # 0015 UTC on Sundays
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: agungos,agungos-ally-budgie,agungos-asus-nvidia,agungos-asus-nvidia-open,agungos-budgie,agungos-budgie-asus,agungos-budgie-asus-nvidia,agungos-budgie-nvidia,agungos-budgie-surface,agungos-budgie-surface-nvidia,agungos-deck,agungos-deck-budgie,agungos-deck-gnome,agungos-deck-nvidia,agungos-framegame-budgie,agungos-gnome,agungos-gnome-asus-nvidia,agungos-gnome-asus-nvidia-open,agungos-gnome-nvidia,agungos-gnome-nvidia-open,agungos-nvidia,agungos-nvidia-open
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7
